//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wells")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tray_id: Uuid,
    pub row_label: String,
    pub column_number: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::freezing_results::Entity")]
    FreezingResults,
    #[sea_orm(
        belongs_to = "super::trays::Entity",
        from = "Column::TrayId",
        to = "super::trays::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Trays,
    #[sea_orm(has_many = "super::well_temperatures::Entity")]
    WellTemperatures,
}

impl Related<super::freezing_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FreezingResults.def()
    }
}

impl Related<super::trays::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trays.def()
    }
}

impl Related<super::well_temperatures::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WellTemperatures.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
