[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[[bin]]
name = "migration"
path = "src/main.rs"


[dependencies]
sea-orm-migration = { version = "1.1.12", features = [
    "sqlx-postgres",
    "sqlx-sqlite",
    "runtime-tokio-rustls",
] }
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
async-trait = "0.1"
uuid = "1.10.0"

[lints.clippy]
pedantic = "allow"
