//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "regions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub experiment_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub region_name: Option<String>,
    pub treatment_id: Option<Uuid>,
    pub wells: Option<Vec<Uuid>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::experiments::Entity",
        from = "Column::ExperimentId",
        to = "super::experiments::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Experiments,
    #[sea_orm(has_many = "super::freezing_results::Entity")]
    FreezingResults,
    #[sea_orm(has_many = "super::inp_concentrations::Entity")]
    InpConcentrations,
    #[sea_orm(
        belongs_to = "super::treatments::Entity",
        from = "Column::TreatmentId",
        to = "super::treatments::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Treatments,
}

impl Related<super::experiments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Experiments.def()
    }
}

impl Related<super::freezing_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FreezingResults.def()
    }
}

impl Related<super::inp_concentrations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InpConcentrations.def()
    }
}

impl Related<super::treatments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Treatments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
