//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "regions")]
pub struct Model {
    pub experiment_id: Uuid,
    pub treatment_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub display_colour_hex: Option<String>,
    pub tray_id: Option<i32>,
    pub col_min: Option<i32>,
    pub row_min: Option<i32>,
    pub col_max: Option<i32>,
    pub row_max: Option<i32>,
    pub dilution_factor: Option<i32>,
    pub created_at: DateTimeWithTimeZone,
    pub last_updated: DateTimeWithTimeZone,
    pub is_background_key: bool,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::experiments::Entity",
        from = "Column::ExperimentId",
        to = "super::experiments::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Experiments,
    #[sea_orm(
        belongs_to = "super::treatments::Entity",
        from = "Column::TreatmentId",
        to = "super::treatments::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Treatments,
}

impl Related<super::experiments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Experiments.def()
    }
}

impl Related<super::treatments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Treatments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
