//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tray_configuration_assignments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tray_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tray_configuration_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub order_sequence: i32,
    pub rotation_degrees: i32,
    pub created_at: DateTimeWithTimeZone,
    pub last_updated: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "crate::routes::trays::configurations::models::Entity",
        from = "Column::TrayConfigurationId",
        to = "crate::routes::trays::configurations::models::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TrayConfigurations,
    #[sea_orm(
        belongs_to = "crate::routes::trays::models::Entity",
        from = "Column::TrayId",
        to = "crate::routes::trays::models::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Trays,
}

impl Related<crate::routes::trays::configurations::models::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrayConfigurations.def()
    }
}

impl Related<crate::routes::trays::models::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trays.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
