//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use chrono::{DateTime, Utc};
use crudcrate::{CRUDResource, EntityToModels};
use sea_orm::entity::prelude::*;
use uuid::Uuid;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, EntityToModels)]
#[sea_orm(table_name = "tray_configurations")]
#[crudcrate(
    generate_router,
    api_struct = "TrayConfiguration",
    name_singular = "tray_configuration",
    name_plural = "tray_configurations",
    description = "This endpoint manages tray configurations, which define the setup of trays used in experiments.",
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[crudcrate(primary_key, update_model = false, create_model = false, on_create = Uuid::new_v4())]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", nullable, unique)]
    #[crudcrate(sortable, filterable, fulltext)]
    pub name: Option<String>,
    #[crudcrate(sortable, filterable)]
    pub experiment_default: bool,
    #[crudcrate(update_model = false, create_model = false, on_create = chrono::Utc::now(), sortable, list_model=false)]
    pub created_at: DateTime<Utc>,
    #[crudcrate(update_model = false, create_model = false, on_update = chrono::Utc::now(), on_create = chrono::Utc::now(), sortable, list_model=false)]
    pub last_updated: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "crate::routes::experiments::models::Entity")]
    Experiments,
    #[sea_orm(has_many = "crate::routes::trays::configuration_assignments::models::Entity")]
    TrayConfigurationAssignments,
}

impl Related<crate::routes::experiments::models::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Experiments.def()
    }
}

impl Related<crate::routes::trays::configuration_assignments::models::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrayConfigurationAssignments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
