//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub mod prelude;

pub mod campaign;
pub mod configs;
pub mod experiments;
pub mod freezing_results;
pub mod images;
pub mod inp_concentrations;
pub mod regions;
pub mod s3_assets;
pub mod samples;
pub mod spatial_ref_sys;
pub mod temperature_probes;
pub mod trays;
pub mod treatments;
pub mod well_temperatures;
pub mod wells;
