//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub use super::campaign::Entity as Campaign;
pub use super::configs::Entity as Configs;
pub use super::experiments::Entity as Experiments;
pub use super::freezing_results::Entity as FreezingResults;
pub use super::images::Entity as Images;
pub use super::inp_concentrations::Entity as InpConcentrations;
pub use super::regions::Entity as Regions;
pub use super::s3_assets::Entity as S3Assets;
pub use super::samples::Entity as Samples;
pub use super::spatial_ref_sys::Entity as SpatialRefSys;
pub use super::temperature_probes::Entity as TemperatureProbes;
pub use super::trays::Entity as Trays;
pub use super::treatments::Entity as Treatments;
pub use super::well_temperatures::Entity as WellTemperatures;
pub use super::wells::Entity as Wells;
