//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "inp_concentrations")]
pub struct Model {
    pub region_id: Uuid,
    pub temperature_celsius: Option<Decimal>,
    pub nm_value: Option<Decimal>,
    pub error: Option<Decimal>,
    pub created_at: DateTimeWithTimeZone,
    pub last_updated: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::regions::Entity",
        from = "Column::RegionId",
        to = "super::regions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Regions,
}

impl Related<super::regions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Regions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
