//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, ToSchema, Deserialize, Serialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "sample_type")]
pub enum SampleType {
    #[sea_orm(string_value = "bulk")]
    Bulk,
    #[sea_orm(string_value = "filter")]
    Filter,
    #[sea_orm(string_value = "blank")]
    Blank,
}
