//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tray_configuration_assignments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tray_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tray_configuration_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub order_sequence: i16,
    pub rotation_degrees: Option<i16>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tray_configurations::Entity",
        from = "Column::TrayConfigurationId",
        to = "super::tray_configurations::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TrayConfigurations,
    #[sea_orm(
        belongs_to = "super::trays::Entity",
        from = "Column::TrayId",
        to = "super::trays::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Trays,
}

impl Related<super::tray_configurations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrayConfigurations.def()
    }
}

impl Related<super::trays::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trays.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
