//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "well_phase_transitions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub well_id: Uuid,
    pub experiment_id: Uuid,
    pub temperature_reading_id: Uuid,
    pub timestamp: DateTimeWithTimeZone,
    pub previous_state: i32,
    pub new_state: i32,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::experiments::Entity",
        from = "Column::ExperimentId",
        to = "super::experiments::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Experiments,
    #[sea_orm(
        belongs_to = "super::temperature_readings::Entity",
        from = "Column::TemperatureReadingId",
        to = "super::temperature_readings::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TemperatureReadings,
    #[sea_orm(
        belongs_to = "super::wells::Entity",
        from = "Column::WellId",
        to = "super::wells::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Wells,
}

impl Related<super::experiments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Experiments.def()
    }
}

impl Related<super::temperature_readings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TemperatureReadings.def()
    }
}

impl Related<super::wells::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wells.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
